site_name: RBTV Pfiffige Ziffern Stats
nav:
  - Episoden: episodes.md
  - Einzelschätzungen: guesses.md
  - Direkter Vergleich: comparison.md
theme:
  name: mkdocs
  custom_dir: theme
markdown_extensions:
  # 2 spaces indented lists
  # https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661
  - mdx_truly_sane_lists
  # Note/warning boxes
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition
