name: build

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Generate markdown
        run: python3 scripts/generate_charts_tables.py
      - name: Publish to github pages
        run: mkdocs gh-deploy
